

display_name: Hiddify
url: https://github.com/hiddify/hiddify-app
license: Other

packager: hiddify
packagerEmail: linux@hiddify.com

icon: assets/images/source/ic_launcher_border.png

keywords:
  - Hiddify
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: Hiddify

requires:
  - libayatana-appindicator-gtk3
  - libcap
  - patchelf

SPEC:
  preamble:
    __requires_exclude: ^libcurl\.so\.4\(CURL_OPENSSL_4\)\(64bit\)$
  body:
    "%post": |
      patchelf --set-rpath /usr/share/hiddify/lib /usr/share/hiddify/hiddify >/dev/null 2>&1 || :
      patchelf --set-rpath /usr/share/hiddify/lib /usr/share/hiddify/HiddifyCli >/dev/null 2>&1 || :
      setcap cap_net_admin=+ep /usr/share/hiddify/hiddify >/dev/null 2>&1 || :
      setcap cap_net_admin=+ep /usr/share/hiddify/HiddifyCli >/dev/null 2>&1 || :

categories:
  - Network

startup_notify: true
# app_links setup for Linux
# https://github.com/llfbandit/app_links/blob/master/doc/README_linux.md
supported_mime_type:
  - x-scheme-handler/hiddify
  - x-scheme-handler/v2ray
  - x-scheme-handler/v2rayn
  - x-scheme-handler/v2rayng
  - x-scheme-handler/clash
  - x-scheme-handler/clashmeta
  - x-scheme-handler/sing-box
